# Generated by Django 3.2 on 2022-06-02 20:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=2200, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('tamanho', models.CharField(max_length=20)),
                ('imagem', models.ImageField(null=True, upload_to='')),
                ('promocao', models.BooleanField(null=True)),
                ('disponivel', models.BooleanField(null=True)),
                ('destaque', models.BooleanField(null=True)),
                ('timestanp', models.DateTimeField(auto_now_add=True)),
                ('item_categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='itemCategoria', to='rdmStore.categoria')),
                ('watchers', models.ManyToManyField(default=[0], null=True, related_name='watchedListing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=2200, null=True)),
                ('comentario_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdmStore.item')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('nomeCompleto', models.CharField(blank=True, max_length=2200)),
                ('informacoes_adicionais', models.CharField(max_length=2200, null=True)),
                ('complemento', models.CharField(max_length=2200, null=True)),
                ('endereco_usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='compra_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frete', models.DecimalField(decimal_places=2, max_digits=6)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('compra_endereco', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='rdmStore.endereco')),
                ('compra_itens', models.ManyToManyField(default=[0], null=True, related_name='comentario_item', to='rdmStore.Item')),
                ('compra_usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
