# Generated by Django 3.2 on 2022-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdmStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='rua',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
