# Generated by Django 3.2 on 2022-02-14 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20220214_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
