# Generated by Django 3.2 on 2021-06-01 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, default=[0], null=True, related_name='watchedListing', to=settings.AUTH_USER_MODEL),
        ),
    ]
