# Generated by Django 3.2 on 2021-06-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_watchers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
